version: '3.7'

services:
  app:
    container_name: link-api
    build:
      context: .
    environment:
      - DB_HOST=postgresql
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  webapp:
    container_name: webapp-dev
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8081:8081
    environment:
      - "CHOKIDAR_USEPOLLING=true"

  postgresql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=app
    ports:
      - 5432:5432

  postgresql-test:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=app
    ports:
      - 25432:5432
